"""create link table

Revision ID: e48ccdc2b788
Revises:
Create Date: 2025-11-17 22:26:28.527265

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e48ccdc2b788"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "link",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("original_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("short_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_link_id"), "link", ["id"], unique=False)
    op.create_index(
        op.f("ix_link_original_url"), "link", ["original_url"], unique=False
    )
    op.create_index(op.f("ix_link_short_url"), "link", ["short_url"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_link_short_url"), table_name="link")
    op.drop_index(op.f("ix_link_original_url"), table_name="link")
    op.drop_index(op.f("ix_link_id"), table_name="link")
    op.drop_table("link")
    # ### end Alembic commands ###
